### PR TITLE
Auto-create Genre on New Movie Addition

### PR DESCRIPTION
**Pull request by azilRababe**
This pull request introduces two main changes to enhance the movie management functionality and improve the file structure. The changes include:

- Automatically create a Genre When Adding a Movie:
To avoid having genres without movies and prevent duplicated genres, I have modified the movie creation process. Now, when adding a new movie, the system automatically creates a genre if it does not exist already.

- File Structure Enhancement:
To improve the file structure and organization, I have made adjustments to the project's file structure. I have restructured the directories, separating concerns and grouping related files together. This restructuring provides a more logical organization and makes it easier to navigate and locate specific files.

### CODE REVIEW

**Comment by orifmilod** [comment]
Hey @azilRababe - I still see the same issue as the previous PR. You see that the 3 first commits are still here. We basically want the last commit only to be in the PR. I am not sure how it's done using `gh` cli - but I think, in the terminal perhaps what you need to do is:
Add the remote (my repo), call it "upstream":
`git remote add upstream https://github.com/orifmilod/iCinema.git`
Fetch all the branches of that remote into remote-tracking branches
`git fetch upstream`
Make sure that you're on your master branch:
`git checkout master`
Rebase your master branch so that any commits of yours that aren't already in upstream/master are replayed on top of that other branch:
`git rebase upstream/master`

Now your master branch will have the upstream (my repo) changes and then make changes and create PR as you would typically do. 

I hope that helps.

**Comment by azilRababe** [comment]
I have followed all the necessary steps, yet unfortunately, I am still encountering the same issue. :(

**Comment by orifmilod** [comment]
@azilRababe I see you created a branch called `upstream` - although that's not an issue; but it might've confused you. `upstream` in my instruction is a [remote](https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes); remote being another git repository. Basically think of it this way; you want to have my changes in my repository (remote) master branch in your repository (remote) master branch. You can validate this by seeing my last commit (https://github.com/orifmilod/iCinema/commit/f383027091f15aad5a1d55ca577160d5dd92cc2e) in your branch. Once you see that, then you can make your changes on top of it. Since you already have your changes in another branch called `upstream` (again unrelated to upstream remote); then all you need to do is [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) it. 


Also extra tip: It's better not to make multiple small commits and call it `Polishing...` or whatever. You can use `git commit --amend` for that. It makes for better software development practice :)

**Comment by azilRababe** [comment]
@orifmilod thank you for providing such valuable information. I appreciate your assistance. I will make every effort to promptly resolve this issue.

**Pull request closed without merging**
